# Generated by Django 5.1.6 on 2025-02-27 20:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagem'),
        ),
    ]
